Express backend pavlishchev v2
baza-trainee/450-kherson-humanitarian-landing-page-backend pull request #5
Opened 2023-09-03 16:24 UTC by velogitara

2023-09-03 16:33 UTC, velogitara commented on .vscode/settings.json
Залетел непонятно как, нужно из репозитория будет удалить

2023-09-03 16:33 UTC, velogitara commented on build/webpack.config.js
файл был пуст без него сборка на сервере хостинга не работала

2023-09-03 16:33 UTC, velogitara commented on config/api/v1/alllowedOrigins.js
разрешает косры для фронта

2023-09-03 16:33 UTC, velogitara commented on config/api/v1/corsOption.js
разрешает косры для фронта

2023-09-03 16:33 UTC, velogitara commented on controllers/api/1/orders/1.js
копия рабочего файла экспорта для ексель файла.пока нужна для разработки

2023-09-03 16:33 UTC, velogitara commented on controllers/auth.js
после мерджа притир сделал свои отступы . я тут ничего не менял

2023-09-03 16:33 UTC, velogitara commented on routes/api1.js
добавил новый роут на GET router.get(
  '/export-order/:orderId'

2023-09-04 20:53 UTC, nerovnia requested changes

2023-09-04 20:53 UTC, nerovnia commented on app.js
CORS в продакшен нам не нужен, нужно сделать так чтобы его можно было просто снести

2023-09-04 20:53 UTC, nerovnia commented on config/api/v1/alllowedOrigins.js
CORS в продакшен нам не нужен, нужно сделать так чтобы его можно было просто снести, для этого все что к нему относится лучше залить в одну папку

2023-09-04 20:53 UTC, nerovnia commented on config/api/v1/corsOption.js
папку CORS можно назвать например где нибудь в утилитах

2023-09-04 20:53 UTC, nerovnia commented on routes/api1.js
POST /api/v1/export/order/{id}  заменить на GET или нужны оба?

2023-09-08 18:46 UTC, merged